name: Bug Report
description: Something is broken in content, tooling, or workflow
title: "[Bug]: "
labels: [bug]
body:
  - type: textarea
    id: summary
    attributes:
      label: What happened?
      placeholder: One sentence summary
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Click-by-click is best.
      placeholder: "1) Go to ...\n2) Click ...\n3) Observe ..."
    validations:
      required: true
  - type: input
    id: expected
    attributes:
      label: Expected
      placeholder: What should have happened?
  - type: input
    id: actual
    attributes:
      label: Actual
      placeholder: What actually happened?
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - P1 - Blocker
        - P2 - Major
        - P3 - Minor
  - type: input
    id: build
    attributes:
      label: Build/Version
      placeholder: e.g., v0.3.2
  - type: textarea
    id: attachments
    attributes:
      label: Evidence
      description: Paste links to screenshots, clips, or logs
