blank_issues_enabled: false
contact_links:
  - name: Ask a general question
    url: https://github.com/ludus-scrinium/ludus-scrinium-hub/discussions
    about: Use Discussions for ideas, questions, and feedback.
