name: Localization Update
description: Track strings ready for translation or QA
title: "[L10n]: "
labels: [localization]
body:
  - type: textarea
    id: strings
    attributes:
      label: Strings/keys
      placeholder: List or link to CSV/JSON
    validations:
      required: true
  - type: textarea
    id: glossary
    attributes:
      label: Glossary/Terminology notes
      placeholder: Terms that must be used or avoided
  - type: dropdown
    id: status
    attributes:
      label: Status
      options:
        - Ready for translation
        - In translation
        - In review
        - QA block
        - Shipped
