name: "Issue"
description: "Issue form for ludus scrinium."
title: "Task:"
labels: ["task"]
assignees: []

body:
  - type: input
    id: owner
    attributes:
      label: Owner
      placeholder: "kaosi"
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options: ["P0","P1","P2","P3"]
      default: 2
  - type: input
    id: start
    attributes:
      label: Start
      placeholder: "YYYY-MM-DD"
  - type: input
    id: due
    attributes:
      label: Due
      placeholder: "YYYY-MM-DD"


  - type: textarea
    id: dod
    attributes:
      label: Definition of Done (tight checklist)
      value: |
        - [ ] 
        - [ ] 

  - type: textarea
    id: tasks
    attributes:
      label: Tasks (keep it short)
      value: |
        - [ ] 
        - [ ] 
        - [ ] 

  - type: textarea
    id: links
    attributes:
      label: Links
      description: "Spec, repo, assets, etc."
      value: |
        Spec: 
        Repo: 
        Assets:
          - 
